local:
  path: uploads/file
  store-path: uploads/file
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: blog
  username: root
  password: root
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  iplimit-count: 15000
  iplimit-time: 3600
timer:
  start: true
  spec: '@daily'
  with_seconds: false
  detail:
    - tableName: sys_operation_records
      compareField: created_at
      interval: 2160h
    - tableName: jwt_blacklists
      compareField: created_at
      interval: 168h
zap:
  level: info
  prefix: '[blog]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true
